# Generated by Django 5.2 on 2025-05-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
       migrations.AddField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='veiculo/fotos'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='preco',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.SmallIntegerField(choices=[(1, 'PRETO'), (2, 'BRANCO'), (3, 'PRATA'), (4, 'VERMELHO'), (5, 'AZUL'), (6, 'VERDE'), (7, 'AMARELO'), (8, 'LARANJA'), (9, 'ROXO'), (10, 'MARROM')]),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.SmallIntegerField(choices=[(1, 'CHEVROLET'), (2, 'FORD'), (3, 'FIAT'), (4, 'VOLKSWAGEN'), (5, 'HONDA'), (6, 'TOYOTA'), (7, 'NISSAN'), (8, 'HYUNDAI'), (9, 'KIA'), (10, 'RENAULT'), (11, 'PEUGEOT'), (12, 'CITROËN'), (13, 'JEEP'), (14, 'CHRYSLER'), (15, 'DODGE'), (16, 'SUBARU'), (17, 'MITSUBISHI'), (18, 'MAZDA'), (19, 'LAND ROVER'), (20, 'JAGUAR')]),
        ),
    ]
