# Generated by Django 5.2 on 2025-04-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='cor',
            new_name='gosto',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='marca',
            new_name='tipo',
        ),
        migrations.AddField(
            model_name='receita',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
