# Generated by Django 5.2 on 2025-04-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0002_rename_cor_receita_gosto_rename_marca_receita_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='gosto',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='tipo',
        ),
    ]
