# Generated by Django 5.2 on 2025-04-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0003_remove_receita_gosto_remove_receita_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='gosto',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'DOCE'), (2, 'SALGADO'), (3, 'OUTRO')], null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='tipo',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'CAFE DA MANHA'), (2, 'LANCHE'), (3, 'ALMOÇO'), (4, 'JANTA'), (5, 'OUTRO')], null=True),
        ),
    ]
