# Generated by Django 5.2 on 2025-05-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0004_receita_gosto_receita_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='veiculo/fotos'),
        ),
    ]
