# Generated by Django 5.2 on 2025-05-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0006_alter_receita_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='ingredientes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='receita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tipo',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'CAFE DA MANHA'), (2, 'LANCHE'), (3, 'ALMOÇO'), (4, 'JANTA'), (6, 'FALSE'), (5, 'OUTRO')], null=True),
        ),
    ]
