# Generated by Django 5.2 on 2025-05-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0007_receita_ingredientes_receita_receita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='ingredientes',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='receita',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
