# Generated by Django 5.2 on 2025-05-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0008_alter_receita_ingredientes_alter_receita_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='ingredientes',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='receita',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
