# Generated by Django 5.2 on 2025-05-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0009_alter_receita_ingredientes_alter_receita_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='tempo_preparo',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
