# Generated by Django 5.2 on 2025-05-25 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0010_receita_tempo_preparo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='dificuldade',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'FACIL'), (2, 'MEDIO'), (3, 'DIFICIL')], null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='porcoes',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
