# Generated by Django 5.2 on 2025-05-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0011_receita_data_criacao_receita_dificuldade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='data_criacao',
        ),
    ]
